### ISSUE TITLE
Estructura de librería 

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-confident-students#2]
[ESTRUCTURA DE LOS MÉTODOS IMPLEMENTADOS EN EL PROYECTO CONFIDENT STUDENTS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-confident-students/files/14725960/ESTRUCTURA.DE.LOS.METODOS.IMPLEMENTADOS.EN.EL.PROYECTO.CONFIDENT.STUDENTS.pdf)

**Comment by JORGELUIS2266** [comment]
De acuerdo a la rúbrica Obtuvieron un porcentaje de 19 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
